### ISSUE TITLE
Tests Failing (and being ignored?)

### ISSUE THREAD

**Issue by jamiejackson** [Ortus-Solutions/docker-commandbox#10]
I'm working on a feature, but the tests seem to be semi-broken?

```
CFCONFIG environment variable was not detected or set
dockercommandbox_sut_1 exited with code 1
```

https://travis-ci.org/Ortus-Solutions/docker-commandbox/jobs/285152238
```
...
sut_1  | INFO: Waiting for server to become available...
sut_1  | INFO: Server engine up and running.
sut_1  | INFO: Configuration processed and server started in 25 seconds.CFCONFIG environment variable was not detected or set
dockercommandbox_sut_1 exited with code 1

The command "docker-compose -f docker-compose.test.yml up --build" exited with 0.
Successfully installed dpl-1.8.43

Installing deploy dependencies
Preparing deploy

Deploying application
Done. Your build exited with 0.
```

**Comment by jclausen** [comment]
@jamiejackson :  Looking in to it now.  Those tests might be failing due to moving the whole `CFCONFIG` environment handling in to the CommandBox `cfconfig` module.

**Comment by jclausen** [comment]
@jamiejackson : This should not be resolved.  Feature away! 👍

**Comment by jamiejackson** [comment]
@jclausen what was the fix? I was running tests locally with:

```sh
BUILD_IMAGE_DOCKERFILE=Dockerfile BUILD_IMAGE_TAG=ortussolutions/commandbox docker-compose -f docker-compose.test.yml up --build
```
...and getting the same results, so I was I'd be able to get passing tests locally, too.

(FYI, I haven't been able to try it again since your message.)

BTW, I guessed at how to run tests. Is there a guide for doing so? (I was hacking on FW/1 recently, and was happy that the testing process was [documented](https://github.com/framework-one/fw1/blob/develop/README.md#running-the-tests), so I could hit the ground running.)
