### ISSUE TITLE
using docker volume for code

### ISSUE THREAD

**Issue by rluijk** [Ortus-Solutions/docker-commandbox#12]
I tried to run the docker ortussolutions/commandbox with a docker volume:
`docker run -p 8080:8080 -p 8443:8443 -v "/var/lib/docker/volumes/romcode/_data:/app" ortussolutions/commandbox`

The docker volume inspect: 
```
docker volume inspect romcode
Returns:
[
    {
        "CreatedAt": "2017-10-09T10:00:48Z",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/romcode/_data",
        "Name": "romcode",
        "Options": {},
        "Scope": "local"
    }
]
```

The server.json is written to the volume and when using the 127.0.01:8080 gives and folder view (directory listing), instead of a working server. I tried on mac and on windows 10. 

Rene

**Comment by jamiejackson** [comment]
Something that might be weird is that it looks like you're using a named volume (Docker-managed) location as a bind mount. Normally, you wouldn't be referring to `/var/lib/docker/volumes/romcode/_data`explicitly. Instead, you would use `-v "romcode:/app"` and _Docker_ would manage that volume and its location (which would _happen_ to be persisted as `/var/lib/docker/volumes/romcode/_data`).

Normally you see bind mounts in some non-Docker-managed location; e.g., `/Users/rluijk/projects/romcode`, then mapped as `-v "/Users/rluijk/projects/romcode:/app"`. If you're just developing locally, for the time being, try it as this kind of bind mount.
