### ISSUE TITLE
Best Practice for Warming up Plugin Installation?

### ISSUE THREAD

**Issue by jamiejackson** [Ortus-Solutions/docker-commandbox#13]
In my Dockerfile, I drop the `cfspreadsheet-lucee-5.lex` in the deployment directory, then warm up:

```
FROM ortussolutions/commandbox:latest
ENV CFENGINE lucee@5.2.3+35
...
# some code that drops the lex into the deploy directory, then...
RUN ${BUILD_DIR}/util/warmup-server.sh
...
```
That works, but it seems the plugin gets fully installed only at runtime (which takes some time).

What's the best practice for warming up a plugin installation?

**Comment by jclausen** [comment]
@jamiejackson : I wasn't aware that the plugin didn't install until the initial application instantiation.  That's not cool.  My suggestion would be to use `curl` inside the container to ping the lucee server admin, which should make sure it's available and ready when the container comes online, live.

The `warmup-server.sh` file won't work because it shuts down the server after it is done, but you can customize it to meet your needs.

**Comment by jamiejackson** [comment]
Ideally, CommandBox would handle plugin installation* and the Docker image would ensure that the plugin installation/warmup completed.

\* Maybe it does already. I'm not familiar with all of its features.

Until then: I don't know whether this is a good approach, but it seems to work. Let me know if you have any ideas for improvement.

```Dockerfile
FROM ortussolutions/commandbox:latest

ENV CFENGINE lucee@5.2.3+35

# warm up server
RUN ${BUILD_DIR}/util/warmup-server.sh
ENV LUCEE_VERSION=5
ENV LUCEE_WEB_INF /root/serverHome/WEB-INF
ENV LUCEE_SERVER ${LUCEE_WEB_INF}/lucee-server
ENV LUCEE_SERVER_CONTEXT ${LUCEE_SERVER}/context
ENV LUCEE_SERVER_DEPLOY ${LUCEE_SERVER}/deploy
ENV LUCEE_WEB ${LUCEE_WEB_INF}/lucee-web
ENV LUCEE_WEB_CONTEXT ${LUCEE_WEB}/context
ENV LUCEE_LIB_DIR ${LUCEE_WEB_INF}/lucee-server/bundles

COPY ./conf/install_cfspreadsheet_lucee${LUCEE_VERSION}.sh /tmp

RUN echo "download/place plugin's *.lex file" \
  && /tmp/install_cfspreadsheet_lucee${LUCEE_VERSION}.sh \
    --deploy-dir="$LUCEE_SERVER_DEPLOY" \
  && echo "warmup plugin" \
  && nohup $BUILD_DIR/run.sh > /dev/null 2>&1 & \
  bg_pid=$! \
  && while ! ls ${LUCEE_LIB_DIR}/cfspreadsheet-*.jar 1> /dev/null 2>&1; do \
       echo "waiting for plugin to warmup"; \
       sleep 1 ;\
     done \
  && kill ${bg_pid} \
  && rm -rf /tmp/*
```
