### ISSUE TITLE
How to add lucee function library in docker-commandbox

### ISSUE THREAD

**Issue by cubortea** [Ortus-Solutions/docker-commandbox#20]
Currently I have some function library in my lucee installation. In my standar lucee installation, I can put the cfc at folder 'WEB-INF\lucee\library\function'

how to include this in docker-commandbox ?

**Comment by jclausen** [comment]
@cubortea : `docker run ...  -v ./my-functions:/root/serverHome/WEB-INF/lucee/library/function  ortussolutions/commandbox:lucee5`   Using the tagged version of the image ensures a warmed up server already exists in that directory.
