### ISSUE TITLE
Box not getting installed on image (due to SSL error?)

### ISSUE THREAD

**Issue by mjclemente** [Ortus-Solutions/docker-commandbox#29]
I forked the repo and attempted to build my own image by running `docker build -t mjclemente/commandbox:latest .`.

At first glance the build looks like it succeeds, but the image isn't usable because `box` doesn't get installed. The logs show that an error occurs during the process of installing CommandBox:

```
Step 26/33 : RUN $BUILD_DIR/util/install-commandbox.sh
 ---> Running in 8f3265dcff65
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   317    0   317    0     0    797      0 --:--:-- --:--:-- --:--:--   798
Archive:  /tmp/box.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /tmp/box.zip or
        /tmp/box.zip.zip, and cannot find /tmp/box.zip.ZIP, period.
/root/build/util/install-commandbox.sh: line 7: box: command not found
 successfully installed
/root/build/util/optimize.sh: line 11: box: command not found
```

It seems like this is being caused by some issue with the SSL certificate. When I try to access the zip file directly in the browser, I'm getting an invalid certificate error (`NET::ERR_CERT_COMMON_NAME_INVALID`). That is, if I attempt to access `https://downloads.ortussolutions.com.s3.amazonaws.com/ortussolutions/commandbox/4.1.0/commandbox-bin-4.1.0.zip`, in any browser, I see something like this:
![ssl-error-chrome](https://user-images.githubusercontent.com/5348419/46581059-c2b02500-c9fe-11e8-9abf-d993c4eff3da.jpg)

I suppose that it could be related to the Symantic/DigitCert trust issue discussed here: https://blog.mozilla.org/security/2018/03/12/distrust-symantec-tls-certificates/

Any ideas? Am I the only one experiencing this? 

(Obviously, this is only going to happen for completely fresh builds; if you have the layers cached you won't experience it because it won't need to go out to do the download. Also, if you're testing access to the zip in the browser, make sure that you don't already have an exception set for the certificate).

**Comment by bdw429s** [comment]
Cross posting my answer from Slack here:

@mjclemente  it would appear AWS changed something in regard to how they do buckets with their domains.
The SSL cert that is used doesn't support many levels of sub domains and since our bucket name contains a period, it looks like multiple sub domains.

I just ran into this issue the other day and the fix was to switch
```
https://downloads.ortussolutions.com.s3.amazonaws.com
```
to
```
https://downloads.ortussolutions.com
```
Where is that old URL being used?  If it's in the Ortus base image, please send a pull or ticket so @jclausen  can look into it.  If it's a script you control, just swap out the domain.

**Comment by mjclemente** [comment]
Hahaha. I saw your response on Slack and responded there first. Ok. 

Two issues here, and the first was my mistake:
1. The image builds fine with the legacy AWS URL when the CommandBox version (`--build-arg COMMANDBOX_VERSION=4.1.0`) is included in the command. I just completely blanked on that. (Perhaps worth discussing if it's worth defaulting the version if not provided? Just a thought)
2. If that URL structure is being removed due to AWS SSL changes, then I guess it should be changed. Would you like a PR for it?

Either way, feel free to close this ticket, as the core reason I opened it is resolved.

Thanks Ortus team!
