### ISSUE TITLE
AWT font classes for POI?

### ISSUE THREAD

**Issue by MordantWastrel** [Ortus-Solutions/docker-commandbox#32]
Linking to a ticket on the lucee-spreadsheet repo. Some features of this library require POI which requires the AWT font classes that seem to be missing from headless OpenJDK:

https://github.com/cfsimplicity/lucee-spreadsheet/issues/161#issuecomment-455609588

I don't know if the future JDK for the Commandbox Docker image will have the same issues with headless v. non-headless -- if not, probably not worth investing any resources into this since presumably you're moving off of OpenJDK 8 anyway.

It also seems like specifying the `headless` JVM option should remove the need for any additional libraries, and Commandbox does that already.

**Comment by jclausen** [comment]
Can you verify that this is no longer an issue. The font packages are now added by default to both images

**Comment by MordantWastrel** [comment]
I don't have a ready test for this because we worked around the relevant features.

**Comment by jclausen** [comment]
OK.  Let me take a look on this one to see if I can add a test for it in the image build
