### ISSUE TITLE
apt-get update fails

### ISSUE THREAD

**Issue by sethstone** [Ortus-Solutions/docker-commandbox#33]
It appears that `apt-get update` no longer works.  I had to add the following to my Dockerfile before running `apt-get update`.

```
# Temporary workaround to fix `apt-get update`
RUN sed -i '/jessie-updates/d' /etc/apt/sources.list \
    && rm /etc/apt/sources.list.d/jessie-backports.list \
    || true
```

Here's the error I was getting: `W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  Unable to find expected entry 'main/binary-amd64/Packages' in Release file (Wrong sources.list entry or malformed file)`

It appears that an upstream image may be based on debian:jessie and it's now deprecated: https://github.com/debuerreotype/docker-debian-artifacts/issues/66

**Comment by jclausen** [comment]
@sethstone:  can you confirm that you have pulled the latest version.  The current image is based on Ubuntu 18.04 https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jre/ubuntu/Dockerfile.hotspot.releases.full

**Comment by sethstone** [comment]
Thanks @jclausen - that was it.  It's a good reminder that I need to run `docker-compose build --pull` occasionally.

**Comment by jclausen** [comment]
No problem!  It happens to all of us. :)
