### ISSUE TITLE
Dockerfile vs Compose

### ISSUE THREAD

**Issue by timsayshey** [Ortus-Solutions/docker-commandbox#4]
I noticed that the dockerfile contains calls to the various bash scripts. However you also include a compose file but the compose file skips all of the bash stuff. If I use compose, I don't need all of the bash stuff then? What is the difference between the two? Thanks!

**Comment by jclausen** [comment]
Hi Tim.

The compose file is using [the compiled image on Docker Hub](https://hub.docker.com/r/ortussolutions/commandbox/).  The `Dockerfile` in this repo is what generates that image and the build process pushes the new versions: https://github.com/Ortus-Solutions/docker-commandbox/blob/master/.travis.yml#L31

The `run.sh` script is the CMD that runs the server on the compiled image, which includes all of the bash scripts

**Comment by timsayshey** [comment]
Thanks Jon, that was best breakdown of the difference between a dockerfile and compose and I searched for hours. On another note, I can't get compose to use my cfconfig file. Here's my compose file:
`version: '2.1'

services:
  app:
    image: ortussolutions/commandbox
    environment:
      PORT: 8080
      SSL_PORT: 8443
      CFCONFIG: /app/cfConfig.json
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1`

And here is my server.json (it seems to use that)

`{
    "web":{
        "rewrites":{
            "enable":"true"
        },
        "http":{
            "port":"8080"
        },
        "ssl":{
            "port":"8443"
        },
        "host":"0.0.0.0"
    },
    "app":{
        "cfengine":"adobe@2016.0.03+300466",
        "serverHomeDirectory":"/root/serverHome"
    },
    "openbrowser":"false",
    "JVM":{
        "args":"-Dmy.environment=local -Dmy.datasource=local -Dex.isAWS=false",
        "minHeapSize":"2048",
        "heapSize":"2048"
    }
}`

**Comment by timsayshey** [comment]
Thanks Jon, that was best breakdown of the difference between a dockerfile and compose and I searched for hours. On another note, I can't access mysql and elasticsearch on my host machine. I also can't get compose to use my cfconfig file. Here's my compose file:

```version: '2.1'

services:
  app:
    image: ortussolutions/commandbox
    environment:
      PORT: 8080
      SSL_PORT: 8443
      CFCONFIG: /app/cfConfig.json
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    networks:
      - dockernet

networks:
  dockernet:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
```

And here is my server.json (it seems to use that)

```
{
    "web":{
        "rewrites":{
            "enable":"true"
        },
        "http":{
            "port":"8080"
        },
        "ssl":{
            "port":"8443"
        },
        "host":"0.0.0.0"
    },
    "app":{
        "cfengine":"adobe@2016.0.03+300466",
        "serverHomeDirectory":"/root/serverHome"
    },
    "openbrowser":"false",
    "JVM":{
        "args":"-Dmy.environment=local -Dmy.datasource=local -Dex.isAWS=false",
        "minHeapSize":"2048",
        "heapSize":"2048"
    }
}
```

**Comment by jclausen** [comment]
This is a known issue that we need to fix, but CFConfig only understands the major version number in the `cfengine`.  I need to update the bash script to parse only the major version.  If you change the engine to `adobe@2016` it should apply the config file correctly.  Right now, it's trying to apply the configuration as `toFormat=adobe@2016.0.3+300466`, which blows up.

Let me know if that solves your issue and feel free to ping me on Slack if I can assist further.

**Comment by timsayshey** [comment]
Awesome! You da man 👊
