### ISSUE TITLE
Module/package Installation Compatibility

### ISSUE THREAD

**Issue by adamrr724** [Ortus-Solutions/docker-commandbox#56]
Using Adobe's CF21 docker image, there is an environment variable available for installing the cfpm packages needed for your environment. Docs found here: https://helpx.adobe.com/coldfusion/using/coldfusion-package-manager.html#interactive

I noticed that with version of [commandbox 5.2.0 the cfpm command was added](https://www.ortussolutions.com/blog/commandbox-forgebox-adobe-coldfusion-2021-and-cfpm), making it easier to install these -- but it does not seem like a new environment variable has been added to automatically install these cfpm packages upon docker container creation using this image. 

1. Will you be adding this as a feature?

2. Can you recommend a straightforward way of implementing an automatic cfpm install of specific packages without having to manually install them after container creation in the meantime?

Thanks so much!

**Comment by jclausen** [comment]
@adamrr724 I will add some additional support for this.  The workaround, in the short-term would be to build with your own Dockerfile, which run the `cfpm` commands and install those modules prior to server start.

**Comment by adamrr724** [comment]
Thanks! We added this into our dockerfile, but had to do the install using cfpm after warming the server, attempts at trying to do it during before that complained of no running commandbox server.

**Comment by jclausen** [comment]
Support is added for `CFPM_INSTALL` and `CFPM_UNINSTALL` environment variables in Commit #619cbbc8705ec430f631799241bd0519fadabd03  .  This will be deployed in the next release.
