### ISSUE TITLE
Enable Admin

### ISSUE THREAD

**Issue by jamiejackson** [Ortus-Solutions/docker-commandbox#6]
When building an image during local development, I want the administrator available. How do I do that?

I tried with:

```
FROM ortussolutions/commandbox:latest

#Hard Code our engine environment
ENV CFENGINE lucee@5.2.3+35

ENV HEADLESS=false

# WARM UP THE SERVER
RUN ${BUILD_DIR}/util/warmup-server.sh
```

However, when I build and run, http://localhost:8080/lucee/admin/web.cfm is unavailable. It's also unavailable if I specify `-e "HEADLESS=false"` with `docker run`.

How do I enable the admin?

**Comment by lmajano** [comment]
Have you exposed the ports on your local machine?

**Comment by jamiejackson** [comment]
I've been exposing `8080`, and the site works, but not the administrator (`Not Found`). Does the admin run on a different port?

**Comment by lmajano** [comment]
No it does not. It should be enabled by default. I am not in my computer. Will test once I get home

Luis Majano
CEO
Ortus Solutions, Corp
www.ortussolutions.com
P/F: 1-888-557-8057
________________________________

**Comment by jclausen** [comment]
@jamiejackson : Can you try this without providing a `HEADLESS` environment variable in your build, at all. If you want it available, by default, you don't need that variable (there is no default set) and it's possible the flag for that is only checking for existence of the variable, not verifying its boolean value

**Comment by jclausen** [comment]
I will, however, create an issue to verify boolean state.

**Comment by jamiejackson** [comment]
I think there may be more to it than the presence or value of the HEADLESS variable. Something about what I'm doing (maybe the warmup?) is blocking the admin.

For example the `Dockerfile` in this comment yields containers without an admin: https://github.com/Ortus-Solutions/docker-commandbox/issues/13#issuecomment-340282820
