### ISSUE TITLE
Admin password is not read from .cfconfig.json in default location

### ISSUE THREAD

**Issue by sbleon** [Ortus-Solutions/docker-commandbox#60]
`cfconfig` will automatically use `/app/.cfconfig.json`, but the startup script will only detect that config file if it's explicitly specified. Thus, having `.cfconfig.json` in the default location does not result in the CF Admin password being set to the value of the `adminPassword` setting.

https://github.com/Ortus-Solutions/docker-commandbox/blob/fbe1331f86113c0552b2b3fa3f970b6573fa1c59/build/run.sh#L138-L151

**Comment by jclausen** [comment]
This will be resolved by commit #e9f9fdf322978de5e3f55481aa05864ce6caa70d and will be deployed in the next update. I've added the ability to check for passwords in the the convention file path.  At some point, in the future, we may delegate all of this fully to CommandBox.

cc/ @bdw429s

**Comment by sbleon** [comment]
Thanks!
