### ISSUE TITLE
_FILE Suffix conventions break when env contains multiple underscores

### ISSUE THREAD

**Issue by mjclemente** [Ortus-Solutions/docker-commandbox#66]
When an env contains multiple underscores, such as `AWS_ACCESS_KEY_ID`, the _FILE suffix convention breaks.

That is, when I set the environment variable equal to a secret (`AWS_ACCESS_KEY_ID_FILE: /run/secrets/aws.access_key_id`), the actual environment variable that gets set is just named `AWS`.

I think this is because of the use of `cut` [here](https://github.com/Ortus-Solutions/docker-commandbox/blob/development/build/util/env-secrets-expand.sh#L36), which appears to be only expecting a single underscore. You can test the syntax used there in the terminal:

```bash
export var=AWS_ACCESS_KEY_ID_FILE
echo $var| cut -d'_' -f 1
// AWS
```

If the script is switched to `#!/bin/bash`, I think updating that portion of the script to `echo ${var%_FILE}` should resolve it.

```bash
export var=AWS_ACCESS_KEY_ID_FILE
echo ${var%_FILE}
// AWS_ACCESS_KEY_ID
```

Happy to add a PR for this if acceptable. Cheers!

**Comment by wphampton** [comment]
Somehow I didn't see this issue when I was searching the past couple of days, and I filed an issue as well #67 and also PR #68

**Comment by jclausen** [comment]
This should be resolved by PR 68.  Let me know if there are any outstanding issues @mjclemente
