### ISSUE TITLE
Docker Secret _FILE Suffix expansion omits pieces

### ISSUE THREAD

**Issue by wphampton** [Ortus-Solutions/docker-commandbox#67]
https://github.com/Ortus-Solutions/docker-commandbox/blob/cc31e59159155f7d8f08c3d87563bc4bce59cb7a/build/util/env-secrets-expand.sh#L36

`REINIT_PASSWORD_FILE` currently becomes `REINIT`

Here's the Linux test of this:
```
echo REINIT_FILE | cut -d'_' -f -1  # Correct, resolves to "REINIT"
echo REINIT_PASSWORD_FILE | cut -d'_' -f -1  # Incorrect, resolves to "REINIT"
echo REINIT_SECRET_PASSWORD_FILE | cut -d'_' -f -1  # Incorrect, resolves to "REINIT"
```

Looking online it seems something like the following might work:
```
var=$(echo $var | rev | cut -d '_' -f 2- | rev);
```

The written test for this only uses a two-part environment variable, so I think that is why it appears to work, but does not match the documentation example for `REINIT_PASSWORD_FILE`.

https://github.com/Ortus-Solutions/docker-commandbox/blob/0fa6dddf626f6b63a3916016007714b701f75fab/build/tests/test.secrets.sh#L9

**Comment by bdw429s** [comment]
This issue has been mentioned on **Ortus Solutions Community**. There might be relevant details there:

https://community.ortussolutions.com/t/docker-commandbox-custom-startup/9215/16

**Comment by jclausen** [comment]
Resolved by the merge of this PR : https://github.com/Ortus-Solutions/docker-commandbox/pull/68
