### ISSUE TITLE
May not be an issue, but a question I can't find in documentation

### ISSUE THREAD

**Issue by damonsential** [Ortus-Solutions/docker-commandbox#73]
How do you specify a serial number and deployment type, and handle activation for Adobe CF licensing with these images?

**Comment by bdw429s** [comment]
@damonsential You  can put it  in the `licenseKey` property of your `.cfconfig.json` or as an env var called `cfconfig_licenseKey`

**Comment by bdw429s** [comment]
Apologies, I didn't actually look up the property name before, I was going from memory.  It's actually just called `license`.

**Comment by bdw429s** [comment]
@damonsential Did you get this working?
