### ISSUE TITLE
TLS cipher limiting for alternate CF engine

### ISSUE THREAD

**Issue by bdh8** [Ortus-Solutions/docker-commandbox#79]
We have been experiencing issues communicating with several services when using the warmed up container for the adobe2023 cf engine (`ortussolutions/commandbox:adobe2023-3.8.4`).  The problem is that SSL handshaking fails due to the ciphers requested by the remote server not being available for use in the container.

I noticed that when I use the default CF engine (`ortussolutions/commandbox:latest`) there is no issue communicating.  I have found that when the `BOX_SERVER_APP_CFENGINE` environment variable is set to an adobe CF engine (as the `ortussolutions/commandbox:adobe2023-3.8.4` image does) the issue presents itself...  If I clear the `BOX_SERVER_APP_CFENGINE` value (`ENV BOX_SERVER_APP_CFENGINE =`) in our docker file, a notification will be shown when the server starts up:

>   You've asked for the engine [lucee@5.4.3+2] to be started,
>   but this server home already has [adobe@2023.0.06+330617] deployed to it
>   In order to get the new version, you need to run 'server forget' on this server and start it again

However, it still uses the adobe CF engine with the JVM17 version of java it needs, AND THERE ARE NO COMMUNICATION ISSUES.

**So it appears that the startup script that is generated in a container is doing something when it thinks it needs to go look for and potentially download the adobe CF engine (either because `BOX_SERVER_APP_CFENGINE` is set or `app.cfengine` is defined in the `server.json` file) that is causing the TLS ciphers in Java to be restricted or limited in some way that persists after the startup script is complete.**

The issue can be observed by adding `-Djavax.net.debug=ssl:handshake` to the jvm args and observing the ClientHello message, specifically the `cipher suites` value, during the execution of a cfhttp command to an https URL.  When the default CF engine is used, the `cipher suites` value will be:

`[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(0xC02C), TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(0xC02B), TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256(0xCCA9), TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(0xC030), TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCA8), TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(0xC02F), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCAA), TLS_DHE_DSS_WITH_AES_256_GCM_SHA384(0x00A3), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_DHE_DSS_WITH_AES_128_GCM_SHA256(0x00A2), TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384(0xC024), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384(0xC028), TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256(0xC023), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256(0xC027), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_DSS_WITH_AES_256_CBC_SHA256(0x006A), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_DHE_DSS_WITH_AES_128_CBC_SHA256(0x0040), TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384(0xC02E), TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384(0xC032), TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256(0xC02D), TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256(0xC031), TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384(0xC026), TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384(0xC02A), TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256(0xC025), TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256(0xC029), TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA(0xC00A), TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(0xC014), TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA(0xC009), TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(0xC013), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_DSS_WITH_AES_256_CBC_SHA(0x0038), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_DHE_DSS_WITH_AES_128_CBC_SHA(0x0032), TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA(0xC005), TLS_ECDH_RSA_WITH_AES_256_CBC_SHA(0xC00F), TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA(0xC004), TLS_ECDH_RSA_WITH_AES_128_CBC_SHA(0xC00E), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]` 

which has the TLSv1.2 `ECDHE` ciphers required by the services we are connecting to, but when a CF engine value is set, (such as `BOX_SERVER_APP_CFENGINE=adobe@2023.0.06+330617`) then the `cipher suites` value is: 

`[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303), TLS_DHE_RSA_WITH_AES_256_GCM_SHA384(0x009F), TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256(0xCCAA), TLS_DHE_DSS_WITH_AES_256_GCM_SHA384(0x00A3), TLS_DHE_RSA_WITH_AES_128_GCM_SHA256(0x009E), TLS_DHE_DSS_WITH_AES_128_GCM_SHA256(0x00A2), TLS_DHE_RSA_WITH_AES_256_CBC_SHA256(0x006B), TLS_DHE_DSS_WITH_AES_256_CBC_SHA256(0x006A), TLS_DHE_RSA_WITH_AES_128_CBC_SHA256(0x0067), TLS_DHE_DSS_WITH_AES_128_CBC_SHA256(0x0040), TLS_DHE_RSA_WITH_AES_256_CBC_SHA(0x0039), TLS_DHE_DSS_WITH_AES_256_CBC_SHA(0x0038), TLS_DHE_RSA_WITH_AES_128_CBC_SHA(0x0033), TLS_DHE_DSS_WITH_AES_128_CBC_SHA(0x0032), TLS_RSA_WITH_AES_256_GCM_SHA384(0x009D), TLS_RSA_WITH_AES_128_GCM_SHA256(0x009C), TLS_RSA_WITH_AES_256_CBC_SHA256(0x003D), TLS_RSA_WITH_AES_128_CBC_SHA256(0x003C), TLS_RSA_WITH_AES_256_CBC_SHA(0x0035), TLS_RSA_WITH_AES_128_CBC_SHA(0x002F), TLS_EMPTY_RENEGOTIATION_INFO_SCSV(0x00FF)]`

causing SSL handshake errors when connecting to servers that do not yet have TLSv1.3 enabled and prefer the `ECDHE` ciphers (or any other set of ciphers that are no longer available for use).

We have experienced this issue trying to access the following services:

`cfhttp(url="https://api.echosign.com/api/rest/v6/baseUris", method="GET", result="result"){};
writeDump(result);`
or
`cfhttp(url="https://awsuat01.integration-api.examity.com/auth", method="POST", result="result"){
	cfhttpparam(type="header", name="Accept", value="application/json");
};
writeDump(result);`

**Comment by jclausen** [comment]
I have seen issues with the cipher suites for ACF in the past - especially when communicating with AWS endpoints.  

The fact that you are reporting that the handshakes succeed when the engine environment variable is removed is extremely curious - since it’s using and starting the same server in both cases.

I’ll see if I can reproduce this tomorrow.  The environment variable is set to prevent attempts to download a new engine.

**Comment by bdw429s** [comment]
You're probably running afoul of the SSL setting covered in this blog post which is disabled by default for Adobe engines.  Trying to start a Lucee server reenables the ECC cipher and probably explains the difference.

https://blog.mattclemente.com/2020/05/23/commandbox-5-cfhttp-ssl-issues/

Try setting this for now and see if it helps.  (Note the syntax for runwar settings will change in CommandBox 6)
```js
{
  "runwar":{
      "args":"--ssl-eccdisable=false"
  }
}
```

**Comment by bdh8** [comment]
Clearing the `BOX_SERVER_APP_CFENGINE` value did also significantly impact performance of the container.  Adding the runwar arg resolves our issue without the negative performance impact.

Thank you Brad for pointing out that blog post and the (more) correct resolution for this problem.
