### ISSUE TITLE
exec /__cacert_entrypoint.sh: exec format error (DigitalOcean Kubernetes)

### ISSUE THREAD

**Issue by i2joseph** [Ortus-Solutions/docker-commandbox#81]
Hi 

I am getting 
exec /__cacert_entrypoint.sh: exec format error
When I deployed the docker on DigitalOcean Kubernetes.

Please help.

Thanks.

**Comment by jclausen** [comment]
Do you have a custom Dockerfile, because there is no file by that name in the base image?

**Comment by jclausen** [comment]
Googling that error a common reason for it that the script was written on Windows and is using CRLF for line breaks, while Linux only recognizes LF

**Comment by i2joseph** [comment]
No I don't use custom Dockerfile. It could be coming from DigitalOcean server.

Here is my Dockerfile:
FROM eclipse-temurin:11-jre-jammy

ENV COMMANDBOX_VERSION 5.9.1
# ARG COMMANDBOX_VERSION

LABEL maintainer "Jon Clausen <jclausen@ortussolutions.com>"
LABEL repository "https://github.com/Ortus-Solutions/docker-commandbox"

# Default to UTF-8 file.encoding
ENV LANG C.UTF-8

# Since alpine runs as a single user, we need to create a "root" direcotry
ENV HOME /root

# Add a working group which any dynamic users can be assigned
ENV WORKGROUP runwar
RUN groupadd $WORKGROUP && usermod -a -G $WORKGROUP root

### Directory Mappings ###
# BIN_DIR = Where the box binary goes
ENV BIN_DIR /usr/local/bin
# LIB_DIR = Where the build files go
ENV LIB_DIR /usr/local/lib
WORKDIR $BIN_DIR

# BUILD_DIR = WHERE runtime scripts go
ENV BUILD_DIR $LIB_DIR/build
WORKDIR $BUILD_DIR

# COMMANDBOX_HOME = Where CommmandBox Lives
ENV COMMANDBOX_HOME=$LIB_DIR/CommandBox

# APP_DIR = the directory where the application runs
ENV APP_DIR /app
WORKDIR $APP_DIR

# Copy file system
COPY ./test/ ${APP_DIR}/
COPY ./build/ ${BUILD_DIR}/
RUN chmod +x $BUILD_DIR/*.sh

# Ensure all runwar users have permission on the build scripts
RUN chown -R $(whoami):${WORKGROUP} $BUILD_DIR


# Basic Dependencies
RUN rm -rf $BUILD_DIR/util/alpine
RUN rm -rf $BUILD_DIR/util/ubi9
RUN ${BUILD_DIR}/util/debian/install-dependencies.sh

# Commandbox Installation
RUN $BUILD_DIR/util/install-commandbox.sh

# Add our custom classes added in the previous step to the java classpath
ENV CLASSPATH="$JAVA_HOME/classes"


# Default Port Environment Variables
ENV PORT 8080
ENV SSL_PORT 8443

# Healthcheck environment variables
ENV HEALTHCHECK_URI "http://127.0.0.1:${PORT}/"

# Our healthcheck interval doesn't allow dynamic intervals - Default is 20s intervals with 15 retries
HEALTHCHECK --interval=20s --timeout=30s --retries=15 CMD curl --fail ${HEALTHCHECK_URI} || exit 1

EXPOSE ${PORT} ${SSL_PORT}

CMD $BUILD_DIR/run.sh

LABEL maintainer "Jon Clausen <jclausen@ortussolutions.com>"
LABEL repository "https://github.com/Ortus-Solutions/docker-commandbox"

ENV BOX_SERVER_APP_CFENGINE lucee@5.4.3+2

ENV LUCEE_EXTENSIONS D062D72F-F8A2-46F0-8CBC91325B2F067B;version=6.3.2

# WARM UP THE SERVER - we skip the declaration so that the default installed Lucee server will be used
RUN ${BUILD_DIR}/util/warmup-server.sh

**Comment by gavinbaumanis** [comment]
We had the same issue when attempting to add our containers to kubernetes.
It is NOT a Digital Ocean problem.
@jclausen's google-fu is the same solution we found a couple  of weeks ago to solve the issue for us.

In the root of your repository add a file "`.gitattributes`"

In that add;
`* text eol=lf`

Then make sure you do a pull/ push / etc...

(We also store the Lucee extensions we use in GIT, too.
And after making the change above we found that GIT complained about our LEX files having been modified.

Similarly to the above, if you add the following line to your "`.gitattributes`" file - you can avoid that, too...
`*.lex binary`
)
